name: Build iOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

    - name: Install dependencies
      run: |
        cd DigiQ  # Asegúrate de usar la carpeta correcta
        pod install --repo-update || true  # Si usas CocoaPods

    - name: Build project
      run: |
        cd DigiQ
        xcodebuild -scheme DigiQ -sdk iphoneos -configuration Release build

    - name: Run tests
      run: |
        cd DigiQ
        xcodebuild test -scheme DigiQ -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
