name: Build iOS App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app/Contents/Developer

    - name: Install dependencies
      run: |
        cd MobileApp-DigiQ-main/DigiQ/DigiQ  # Ruta corregida
        xcodebuild clean -scheme DigiQ -sdk iphoneos -configuration Release

    - name: Build project
      run: |
        cd MobileApp-DigiQ-main/DigiQ
        xcodebuild -project DigiQ.xcodeproj -scheme DigiQ -sdk iphoneos -configuration Release build

    - name: Run tests
      run: |
        cd MobileApp-DigiQ-main/DigiQ
        xcodebuild test -project DigiQ.xcodeproj -scheme DigiQ -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
