name: Build iOS App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app/Contents/Developer

    - name: Verify project structure
      run: |
        ls -la
        cd DigiQ
        ls -la  # Muestra los archivos dentro de DigiQ para depuración

    - name: Clean and build project
      run: |
        cd DigiQ
        xcodebuild clean
        if [ -f "DigiQ.xcworkspace" ]; then
          xcodebuild -workspace DigiQ.xcworkspace -scheme DigiQ -sdk iphoneos -configuration Release build
        else
          xcodebuild -project DigiQ.xcodeproj -scheme DigiQ -sdk iphoneos -configuration Release build
        fi

    - name: Run tests
      run: |
        cd DigiQ
        xcodebuild test -scheme DigiQ -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
